apiVersion: v1
kind: Service
metadata:
  name: binder
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    name: binder-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
