# pre-commit is a tool to automatically do tasks before committing.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
repos:
  # Python code formatting
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--target-version=py36]

  # Shell script code formatting
  - repo: https://github.com/lovesegfault/beautysh
    rev: 6.0.1
    hooks:
      - id: beautysh

  # Reset changes by chartpress
  - repo: local
    hooks:
      - id: chartpress
        name: chartpress --reset
        files: jupyterhub/Chart.yaml|jupyterhub/values.yaml
        description: Run `chartpress --reset` to clean up helm charts before committing.
        entry: chartpress --reset
        language: system
        pass_filenames: false

  # Check chart for possible issues
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: helmlint

# The hooks in this file are automatically installed by pre-commit, but shellcheck
# must be manually installed so it is included in .pre-commit-shellcheck.yaml
# instead. To run it:
#   pre-commit run --config .pre-commit-shellcheck.yaml --all-files
