os: linux
dist: bionic
language: python
python:
  - 3.7
git:
  ## depth set to false overrides travis default behavior to use shallow clones
  ## with depth 50 that can cause issues
  ##
  ## ref: https://github.com/jupyterhub/chartpress#shallow-clones
  ##
  depth: false
services:
  - docker

stages:
  - name: publish
    if: tag IS present OR ( branch IN (master) AND type IN (push) )
  - name: test

before_install:
  # Exit immediately if a command exits with a non-zero status.
  - set -e
  - . ci/common
  # NOTE: The latest docker python package (4.3.0) requires a more modern docker
  #       version (newer than 18.06.0-ce / API version: 1.38) which is not yet
  #       available on travis.
  - pip install "docker~=4.2.0"

# The default install script below will prepare a k8s cluster to work with, but
# not install JupyterHub itself, as upgrade tests may want to make multiple
# installations in sequence etc.
install:
  # Fix to avoid rebuilding images already built
  - remove_docker_mirror_on_travis

script:
  # Install JupyterHub
  - helm install jupyterhub ./jupyterhub --values dev-config.yaml
  - await_jupyterhub
  - await_autohttps_tls_cert_acquisition

  # Run tests
  - pytest --verbose --exitfirst ./tests || (full_namespace_report && exit 1)

env:
  ## Global environment variables will act as defaults, jobs will override them
  ## k3s versions:  https://github.com/rancher/k3s/releases
  ## helm versions: https://github.com/helm/helm/releases
  global:
    - K3S_VERSION=v1.19.3+k3s1
    - HELM_VERSION=v3.3.4

jobs:
  ## define individual jobs that can rely on defaults from above
  include:

    - stage: publish
      name: publish:helm-chart
      install:
        - pip install --no-cache-dir -r dev-requirements.txt
      script:
        - setup_helm
        - remove_docker_mirror_on_travis
        - ./ci/publish
      env:
        ## encrypted environment variables DOCKER_USERNAME and DOCKER_PASSWORD,
        ## used in the publish script to push built docker images to docker hub.
        ##
        ## ref: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
        - secure: jpFpbMccpjGP+otWH2Z03VFdtR9AAu2vzrNxsoZ3IvJvrO4MfzYJ3uSCDQuB0NG9gBgaAscpTJtliPTEi7njXHLcsFeWXLUmeBEHLozYxfzDQzMvW3EYdNWcC7oVAAt3de0i0ojw9rGswiofhbu2dAe+Xd2bejv1+PVJcEC3SRPGy17kb6bme6gD3zty5ft4VpzP0nomUNqfZBRLUYxSZuKlHJaZ6Nuq434rKmXrcN6uy+eEWDorTbjyM22IIYgUmrhg++Qtu/MBR7/rriPhyRltCU14361bcxqyq2Hw+HNG8D3hsqo5TiEiYwxOQcXRgddL+Ci6/y0L1EvqOQc+1V8ycwNs2oNicwNgSn5A+9HpF495Kae039hGtj2Gpt4IbplSYwKFq/sFTq+CekxdD2YVQmGvsjep4bNVL66o2RSZVAW1Bg/G8/sSe3BwgD8IToy9+1NHPPuaVupeukRqNyUDcVvWH8hdb8AkXYY87+546etYDpn91GQnhTEberKbXX4UCmpKNXpXoprLE8nQLGb6TIoHPTyA+RRNQ4erDzMjqF43UVmhOZTtkGaRgIWK7vDAKpLUnuOguuhJUNpYpRggGQsMV8cZnaCumy5OFUf6i6rfN0Ru6a+/Bm7grJiAcnZlU7igaxgI38QaJgCKcqqzIImdcRYNQC74/Ok/1oM=
        - secure: BK++GwKVPoS0iG8aB7wQ13daTgJR9MifHA+l9xr/tSZ3SUL6nc7kjxLbliRQJCqT9lcOODsd+v2u9PziEzBp0CCh67ftFxJw8riP2+FgdmHTK4yav9QpSwoBJHhV2SgBMGlXiqdUVC7wpgjzzK63V8abvzAhXkthWPl3kYpUI//xGYyuBNXVHEOImHB3F1M5bn90lflFtRfq2iH5FigGesMi2BFfTVeqvbzZVZrAs0E1/NRdO+/cRq0c9aRpNLkh254k1tcKbUvULQq1iLQuHN2Ramn3NgNnx93sbwp1e7ZjmETbjr9cwMIDg5mh25H0Rjf2Nn8cqHbBCWzoMkjZW097HRVDYht2kJZQIbQcaxX38DW6vykUwGWSBAWbtvCUwYwU57s/dIbSYUTQErkYYmhiq52cdOtnxZ2/ULoElCVyR8lTmQuANJrq9YFC9q1ly69YuMWWnFgwxWpK1JCgAJGELgj5EvcghEtNmkEFh5f6pmbKBE7PKQPTovzNKcdRauR/L+MsmhVYukCfNZq57LrruIQIX1GQNw9w3Ck8P4EPtNjdI4umCSy6nZSyTevWgVTmIP9EwXa5Cap32ZU+iDtw+wUBAr3sjROJOYGKlL/ktWsWbjog5hIG0rrb8PbgOfbLRZSEYGL9sYsyXXyW5oI37lB7AqG6D7vOA4TdmTQ=
