language: python
sudo: required
python:
- 3.4
services:
- docker
install:
- pip install --no-cache-dir pyyaml sphinx doctr
- curl -ssL https://storage.googleapis.com/kubernetes-helm/helm-v2.5.1-linux-amd64.tar.gz
  | sudo tar -xz -C /usr/local/bin --strip-components 1 linux-amd64/helm
- sudo chmod +x /usr/local/bin/helm
- "/usr/local/bin/helm init --client-only"
script:
- cd doc && make html && cd .. && doctr deploy .
- docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
- "./build.py build --commit-range ${TRAVIS_COMMIT_RANGE} --push"
before_install:
- openssl aes-256-cbc -K $encrypted_7d96c3e8d1a2_key -iv $encrypted_7d96c3e8d1a2_iv
  -in travis.enc -out travis -d
- chmod 0400 travis

env:
  global:
  - secure: "WNCupFWu//w/txKmjZn9LwiqvXg8qcj+aKbXRR+DZ9PQMRtngqVHVqjlZ3ghjcXJ5OTd8IpRiAVPGluayZRpLikiiZHLVE0U7fYpsErPl7IbJ+vJ3vhwcJuUJzOGt0a0cgvwudEdFF56LeAqy3YnZPDpQ/k8+edMq2gMwfKGo3aHzwO6eIaeo65GbmNHh/vMpBDhJDUeWvZOWifIO89AWcfYch337uIXWTR2D/fh2rlqQSxY8IvcOdnbQ2NjLv/m516rNfwindtDbPeyqMCeH2plZsgOGTl7IOaw5IskwE0uwV9b8P6zeAuX63sZtRj3Z1wZE2EFC2H+YWuhtRiHNdEhAjQWgh+FoiOVsMgOUZEbnfNhODFpQ/oqGdaPjiEoE3oS0DeF78Fy5nEgQmXE2anV6+9FZsIZYnHMcr2AHpM9oE2PJgorv+LkhCTEMVIKHEeG7nmQKyP9/ziaDhxxS7fxR7ESqJLR+Y4qD16PQeDpNmgHgrWw/lsoFJnBSw1HDbOKSoQBm3h5viGJ+kSGuYxLbWoRVQqZdKinO3USr+oB31fqH0cmQgNjkVMBdZ0aVhYUMBp+sx5OblFpoeQAMgKP6eiifplBIY9LCL2y3cjDhm3ayOxfyll7PhqBPtDHbPDpAjBDPkLH6cXOUuPwPu2YfkNEUPFeKqhG/jG4lcU="
  - secure: FbM+8QAYUVz4whHm2yoBrGmny1ncImqRwZeL3iH1P4I9nkgh3yyTuMbBavbcUI0ZohQx92E3IJwfKn0I67FEB88DnUR6nDgd92EixdIB75SltMSi/PzDxMpBIuyZLCPGX/Ip+AtzPmWv1xJrWTk1TcknNMAtoR/ecYawccTOQy8TzaUNtgvQJmILcyo9UO+wdrN7KTIlsXLqOBuJY7wDe5G5iDK0Ye0K/lahDi4IUfpvbaZQcZ7so1hg8TH0DY8wOyU9+VQ1jyegr5OO0rcrOK2jAjc1xks6NnqXikrPUZsukzW/f+Q3PiSRCWXOyVDL3h9iiDGKIgf0IOrrwSBnmtWMmQeTew1noyYiuK8KGT8Y7x/Sapp39OrOMT14Oaiw1uaVPADhYRraGo3pXbJ0EDRXinwfWF4GMhqJH6ygqM5Su8QnphVOWexTiJZNRHHnLojmnYhcyQrpND3qQQi+ApAw/QKS4uxMlu4fxFk2slAtsPwdqNVvm8nVlfmHuTaed7ZP+kYfcCNQZeqWuWpJZ/6L9h4/fG54yB6moY8EDH/KTkVoo6w44MIpJTbTUTlfYdhkv5TLTWmWk5HwwRWn7WZvYeDgVBgiI1biPRpDRcZ0o+FlzzKXo/cyP10Axd4zrvE924UD7jEJarwGnZFrGMUV6hJ5h/Kxc+U3yE3RTsU=
  - secure: RdG7zCRCx2I8FsPbMNSFSmqCJTPmEx+sZCcWi1Hxv0PKLaLN3Q+7PqjfPWmJvO6pfFlCzbImt5UAHvFz11r1+xWYPF8lJySNSeMSYERHalQ4rdvdsUfz1+C/WWxrVt8TmG5kNtMuvMWiv37oPRCbtKpiKEBSK4Sgdg7I+BDdVRxxNh8hLqBVujxb2He6V71c81EIwGukgmbb06MNYHIDdoxzijbm/sCQrOCTi7SCIHjzxVoYVFQlwuNP9nGXP0bmwr47E5w9hI0pB6zLc/S0TrHwjM/8d5gwuP1p5A2UgybeeyHAVXX1D8FmPm6fsdwZ/phKhy2emKDItHnJFZiTN7uQZikIowo+l6XsflRgC2NLxg8fP4jLnrAlvfO00nYS2jDGXadaXNnlPLQRn/9A4EYMegI7hfZlVUcCuOaiama8r0dxusZnKq1yIcTId2pa/4KZrwbhQ4+Av0+gxIXfOtUhw1lGrwZVNx6SOasFIOXo8sId1SZVbSLL4q4DyFTclXBOzw2Jg2BNOmSC6U8eRBwa7GVOf8dCh/CBqgPMsdd2dJxUXzeCe+22+l46HXsEO7ReGL68p//795HCPZy/TYJQkn+6hzDLh/0TYIVgmRR17+kUGc/4IKotQVrvBrK5W1sYrGy84w/lYv1vVMvkYJH6NGixXYLpEeqMJDzyIKQ=
