# FIXME: All network policies are disabled as k3s fail to enforce them robustly,
# see this issue for more info:
# https://github.com/rancher/k3s/issues/947#issuecomment-627641541

proxy:
  secretToken: pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: letsencrypt
    hosts: [local.jovyan.org]
    letsencrypt:
      contactEmail: 'jovyan@jupyter.test'
      acmeServer: https://pebble/dir
  traefik:
    extraVolumes:
      - name: pebble-root-cert
        configMap:
          name: pebble
    extraVolumeMounts:
      - name: pebble-root-cert
        subPath: root-cert.pem
        mountPath: /etc/pebble/root-cert.pem
    extraEnv:
      - name: LEGO_CA_CERTIFICATES
        value: /etc/pebble/root-cert.pem
  networkPolicy:
    enabled: false
    egress: []  # overrides allowance of 0.0.0.0/0
  chp:
    resources:
      requests:
        memory: 0
        cpu: 0

hub:
  cookieSecret: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
  db:
    type: sqlite-memory
  services:
    test:
      admin: true
      apiToken: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  networkPolicy:
    enabled: false
    egress:  # overrides allowance of 0.0.0.0/0
      # In kind/k3s clusters the Kubernetes API server is exposing this port
      - ports:
        - protocol: TCP
          port: 6443
  resources:
    requests:
      memory: 0
      cpu: 0

singleuser:
  storage:
    type: none
  memory:
    guarantee: null
  networkPolicy:
    enabled: false
    # For testing purposes in test_singleuser_netpol
    egress:
      - to:
        - ipBlock:
            cidr: 104.28.9.110/32       # jupyter.org 1
        - ipBlock:
            cidr: 104.28.8.110/32       # jupyter.org 2

prePuller:
  hook:
    enabled: false

debug:
  enabled: true

# A few values for the Pebble Helm chart, allowing us to fool Pebble to resolve
# all .test domains to our proxy-public service.
coredns:
  corefileSegment: |-
    template ANY ANY local.jovyan.org {
      answer "{{ .Name }} 60 IN CNAME proxy-public.{$PEBBLE_NAMESPACE}.svc.cluster.local"
    }
