proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: letsencrypt
    hosts:
      - local.jovyan.org
    letsencrypt:
      contactEmail: "jovyan@jupyter.test"
      acmeServer: https://pebble/dir
  traefik:
    extraVolumes:
      - name: pebble-root-cert
        configMap:
          name: pebble
    extraVolumeMounts:
      - name: pebble-root-cert
        subPath: root-cert.pem
        mountPath: /etc/pebble/root-cert.pem
    extraEnv:
      LEGO_CA_CERTIFICATES: /etc/pebble/root-cert.pem
  chp:
    resources:
      requests:
        memory: 0
        cpu: 0
    networkPolicy:
      egress: [] # overrides allowance of 0.0.0.0/0

hub:
  db:
    type: sqlite-memory
  services:
    test:
      admin: true
      apiToken: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  networkPolicy:
    egress: # overrides allowance of 0.0.0.0/0
      # In kind/k3s clusters the Kubernetes API server is exposing this port
      - ports:
          - protocol: TCP
            port: 6443
  resources:
    requests:
      memory: 0
      cpu: 0
  extraFiles:
    binaryData.txt: &binaryData
      mountPath: /tmp/
      mode: 0666
      binaryData: aGVsbG8gd29ybGQhCg==
    binaryData2.txt: &binaryData2
      mountPath: /tmp/dir1
      mode: 0666
      binaryData: aGVsbG8gd29ybGQhCg==
    stringData.txt: &stringData
      mountPath: /tmp
      mode: 0666
      stringData: hello world!
    stringData2.txt: &stringData2
      mountPath: /tmp/dir1/
      mode: 0666
      stringData: hello world!
    data.yaml: &data
      mountPath: /etc/test
      mode: 0444
      data:
        config:
          map:
            number: 123
            string: "hi"
          list: [1, 2]
    data.yml: *data
    data.json: *data
    data.toml: *data

singleuser:
  extraFiles:
    binaryData.txt: *binaryData
    binaryData2.txt: *binaryData2
    stringData.txt: *stringData
    stringData2.txt: *stringData2
    data.yaml: *data
    data.yml: *data
    data.json: *data
    data.toml: *data
  storage:
    type: none
  memory:
    guarantee: null
  networkPolicy:
    # For testing purposes in test_singleuser_netpol
    egress:
      - to:
          # jupyter.org has multiple IPs associated with it, among them are these
          # two. We explicitly allow access to one, but leave out the the other.
          - ipBlock:
              cidr: 104.28.8.110/32
        # - ipBlock:
        #     cidr: 104.28.9.110/32
  extraEnv:
    TEST_ENV_FIELDREF_TO_NAMESPACE:
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

prePuller:
  hook:
    enabled: false

scheduling:
  userScheduler:
    enabled: true
    replicas: 2
    logLevel: 10

debug:
  enabled: true
