kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-config
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
{{- $values := pick .Values "auth" "cull" "hub" "scheduling" "singleuser" }}
{{- /* trim secret values. Update here if new secrets are added! */ -}}
{{- /* make a copy of values.auth to avoid modifying the original */ -}}
{{- $_ := set $values "auth" (merge dict .Values.auth) }}
{{- $_ := set $values.auth "state" (omit $values.auth.state "cryptoKey") }}
{{- $_ := set $values "hub" (omit $values.hub "cookieSecret") -}}
{{- range $key, $service := $values.hub.services }}
  {{- if $service.apiToken }}
    {{- $_ := set $values.hub.services $key (omit $service "apiToken") }}
  {{- end }}
{{- end }}
{{- /* copy values.singleuser */ -}}
{{- $_ := set $values "singleuser" (omit .Values.singleuser "imagePullSecret") }}
{{- $_ := set $values.singleuser "imagePullSecret" (omit .Values.singleuser.imagePullSecret "password") }}
  values.yaml: |
    {{- $values | toYaml | nindent 4 }}
