{{ if and .Values.cull.enabled .Values.cull.maxAge }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pod-culler
  labels:
    app: jupyterhub
    component: pod-culler
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "*/{{ .Values.cull.podCuller.intervalMinutes }} * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: jupyterhub
            component: pod-culler
            release: {{ .Release.Name }}
            heritage: {{ .Release.Service }}
        spec:
          restartPolicy: Never
          {{ if .Values.rbac.enabled }}
          serviceAccountName: pod-culler
          {{- end }}
          containers:
          - name: culler
            image: {{ .Values.cull.podCuller.image.name }}:{{ .Values.cull.podCuller.image.tag }}
            resources:
              requests:
                memory: 100Mi
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MAX_AGE
              value: {{ .Values.cull.maxAge | quote }}
{{ end }}
