{{- if and .Values.cull.enabled .Values.cull.maxAge -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-culler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "jupyterhub.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: pod-culler
      {{- end }}
      containers:
        - name: culler
          image: {{ .Values.cull.podCuller.image.name }}:{{ .Values.cull.podCuller.image.tag }}
          resources:
            requests:
              memory: 100Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR
              value: "component=singleuser-server"
            - name: MAX_AGE
              value: {{ .Values.cull.maxAge | quote }}
            - name: CULL_INTERVAL
              value: {{ .Values.cull.every | quote }}
{{- end }}
