apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/hub-secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
        checksum/proxy-secret: {{ include (print $.Template.BasePath "/proxy/secret.yaml") . | sha256sum }}
      labels:
        name: proxy
        component: proxy
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      nodeSelector: {{ toJson .Values.proxy.nodeSelector }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values: ['hub']
                    - key: release
                      operator: In
                      values: [ {{ .Release.Name | quote }} ]
      containers:
        - name: chp
          image: {{ .Values.proxy.chp.image.name }}:{{ .Values.proxy.chp.image.tag }}
          {{- if .Values.proxy.chp.cmd }}
          command: {{ toJson .Values.proxy.chp.cmd }}
          {{- end }}
          resources:
{{ toYaml .Values.proxy.chp.resources | indent 12 }}
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hub-secret
                  key: proxy.token
          imagePullPolicy: {{ .Values.proxy.chp.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: proxy-public
            - containerPort: 8001
              name: api
      terminationGracePeriodSeconds: 60
