apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
  {{ if .Values.name }}namespace: {{ .Values.name }} {{ end }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy-pod
        {{ if .Values.proxy.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.proxy.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
      - name: proxy-container
        image: {{ .Values.proxy.image.name }}:{{ .Values.proxy.image.tag }}
        command: {{ toJson .Values.proxy.cmd }}
        resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
        env:
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub-secret
                key: proxy.token
        ports:
          - containerPort: 8000
            name: proxy-public
          - containerPort: 8001
            name: api
