{{- if and .Values.proxy.https.enabled (eq .Values.proxy.https.type "auto") }}
{{- if .Values.proxy.hosts }}
# This is solely used to provide auto HTTPS with our bundled kube-lego
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-internal
  annotations:
    # Set a high limit for max size of notebooks that we can save. Default is 1M
    ingress.kubernetes.io/proxy-body-size: 64m
    # These can all be overridden by setting .Values.proxy.ingress.annotations
    kubernetes.io/ingress.provider: nginx
    kubernetes.io/ingress.class: jupyterhub-proxy-tls
    hub.jupyter.org/tls-terminator: "true"
spec:
  rules:
    {{- range $host := .Values.proxy.hosts }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: proxy-http
              servicePort: 8000
      host: {{ $host }}
    {{- end }}
  tls:
    - secretName: kubelego-tls-proxy-{{ .Release.Name }}
      hosts:
{{ toYaml .Values.proxy.hosts | indent 8 }}
{{- end }}
{{- end }}
