{{- $HTTPS := .Values.proxy.https.enabled -}}
# Automatic HTTPS via Let's Encrypt requires list of hostnames to be turned on
{{- $autoHTTPS := and $HTTPS (and (eq .Values.proxy.https.type "letsencrypt") .Values.proxy.https.hosts) -}}
# Manual HTTPS with user provided certs does not require list of hostnames
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
# Offloading HTTPS to external LoadBalancer does not require list of hostnames either
{{- $offloadHTTPS := and $HTTPS (eq .Values.proxy.https.type "offload") -}}
apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  labels:
    {{- $_ := merge (dict "componentSuffix" "-api") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - port: 8001
      targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-public
  labels:
    {{- $_ := merge (dict "componentSuffix" "-public") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
    {{- if .Values.proxy.service.labels }}
    {{- .Values.proxy.service.labels | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
    {{- .Values.proxy.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- if $autoHTTPS }}
    component: autohttps
    {{- else }}
    component: proxy
    {{- end }}
    release: {{ .Release.Name }}
  ports:
    {{- if or $autoHTTPS (or $manualHTTPS $offloadHTTPS) }}
    - name: https
      port: 443
      # When HTTPS is handled outside our helm chart, pass traffic
      # coming in via port 443 to port 80. Termination happens
      # outside of kubernetes somehow
      {{- if $offloadHTTPS }}
      targetPort: http
      {{- else }}
      targetPort: https
      {{- end }}
      {{- with .Values.proxy.service.nodePorts.https }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
    - name: http
      port: 80
      targetPort: http
      {{- with .Values.proxy.service.nodePorts.http }}
      nodePort: {{ . }}
      {{- end }}
  type: {{ .Values.proxy.service.type }}
  {{- with .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if eq .Values.proxy.service.type "LoadBalancer" }}
  {{- with .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- end }}
