{{ define "jupyterhub.imagePuller.daemonset" }}
# template that returns an imagePuller daemonset
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generateName: image-puller-
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
        app: jupyterhub
        component: image-puller
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: jupyterhub
        component: image-puller
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: image-pull
        image: {{ .Values.imagePuller.image.name }}:{{ .Values.imagePuller.image.tag }}
        imagePullPolicy: Always
        env:
          - name: IMAGE_NAME
            value: {{ .Values.singleuser.image.name }}
          - name: IMAGE_TAG
            value: {{ .Values.singleuser.image.tag }}
            {{ range $key, $value := .Values.imagePuller.extraEnv }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
            {{ end }}
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
{{- end }}
