{{ define "jupyterhub.imagePuller.daemonset" }}
# template that returns an imagePuller daemonset
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: jupyterhub
    component: image-puller
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  generateName: image-puller-
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
        app: jupyterhub
        component: image-puller
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: jupyterhub
        component: image-puller
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      initContainers:
      - name: image-pull
        image: {{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - echo "Pulling complete"
      containers:
      - name: pause
        image: gcr.io/google_containers/pause:3.0
{{- end }}
