version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout
      # Python env
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV

      - run:
          name: Install doc dependencies
          command: |
            pip install --upgrade pip setuptools
            pip install --user -r doc/doc-requirements.txt

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html

      - store_artifacts:
          path: doc/build/html/
          destination: html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
