{{- if .Values.scheduling.userScheduler.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: user-scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  # ref: https://kubernetes.io/docs/reference/scheduling/config/
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: {{ .Release.Name }}-user-scheduler
        plugins:
          {{- if .Values.scheduling.userScheduler.plugins }}
          {{- .Values.scheduling.userScheduler.plugins | toYaml | trimSuffix "\n" | nindent 10 }}
          {{- else }}
          score:
            disabled:
              - name: NodeResourcesLeastAllocated
              - name: NodeResourcesBalancedAllocation
            enabled:
              - name: NodeResourcesMostAllocated
          {{- end }}
{{- end }}
