{{- if .Values.scheduling.userScheduler.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: user-scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  # ref: https://kubernetes.io/docs/reference/scheduling/config/
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      resourceLock: endpoints
      resourceName: user-scheduler-lock
      resourceNamespace: {{ .Release.Namespace }}
    profiles:
      - schedulerName: {{ .Release.Name }}-user-scheduler
        plugins:
          {{- if .Values.scheduling.userScheduler.plugins }}
          {{- .Values.scheduling.userScheduler.plugins | toYaml | trimSuffix "\n" | nindent 10 }}
          {{- else }}
          score:
            disabled:
              - name: ImageLocality
              - name: NodeResourcesLeastAllocated
              - name: NodeResourcesBalancedAllocation
              - name: SelectorSpread
            enabled:
              - name: NodeResourcesMostAllocated
          {{- end }}

  {{- $defaultPolicy := .Files.Get "files/userscheduler-defaultpolicy.yaml" | fromYaml }}
  policy.cfg: {{ .Values.scheduling.userScheduler.policy | default $defaultPolicy | toJson | quote }}
{{- end }}
