{{- if .Values.scheduling.userScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduling.userScheduler.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/scheduling/user-scheduler/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: user-scheduler
      {{- end }}
      {{- if .Values.scheduling.podPriority.enabled }}
      priorityClassName: {{ .Release.Name }}-default-priority
      {{- end }}
      nodeSelector: {{ toJson .Values.scheduling.userScheduler.nodeSelector }}
      {{- include "jupyterhub.coreAffinity" . | nindent 6 }}
      volumes:
        - name: config
          configMap:
            name: user-scheduler
      containers:
        - name: user-scheduler
          # NOTE: When kube-scheduler 1.17+ fail to find CSINode resource in the
          #       cluster, they fail to startup. Due to this, we fallback to the
          #       latest functional version with its legacy configuration.
          {{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSINode" }}
          image: {{ .Values.scheduling.userScheduler.image.name }}:{{ .Values.scheduling.userScheduler.image.tag }}
          {{- else }}
          image: {{ .Values.scheduling.userScheduler.image.name }}:v1.16.15
          {{- end }}
          command:
            # NOTE: --leader-elect-... (new) and --lock-object-... (deprecated)
            #       flags are silently ignored in favor of whats defined in the
            #       passed KubeSchedulerConfiguration whenever --config is
            #       passed.
            #
            # ref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
            # ref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
            - /usr/local/bin/kube-scheduler
            {{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSINode" }}
            - --config=/etc/user-scheduler/config.yaml
            {{- else }}
            - --scheduler-name={{ .Release.Name }}-user-scheduler
            - --policy-config-file=/etc/user-scheduler/policy.cfg
            - --lock-object-name=user-scheduler-lock
            - --lock-object-namespace={{ .Release.Namespace }}
            {{- end }}
            - --v={{ .Values.scheduling.userScheduler.logLevel | default 4 }}
          volumeMounts:
            - mountPath: /etc/user-scheduler
              name: config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            {{- .Values.scheduling.userScheduler.resources | toYaml | trimSuffix "\n" | nindent 12 }}
{{- end }}
