{{ if .Values.prePuller.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-puller-{{ .Release.Time.Seconds }}-{{.Release.Name}}-{{.Release.Revision}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      restartPolicy: Never
      {{ if .Values.rbac.enabled }}
      serviceAccountName: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
      {{- end }}
      containers:
        - image: {{ .Values.prePuller.image.name }}:{{ .Values.prePuller.image.tag }}
          name: pre-puller
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DAEMONSET_SPEC
              value: {{ toJson (fromYaml (include "jupyterhub.imagePuller.daemonset" .)) | quote }}
            - name: IMAGE
              value: "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"
{{ end }}
