{{ if .Values.prePuller.hook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-puller-{{ .Release.Time.Seconds }}-{{.Release.Name}}-{{.Release.Revision}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      restartPolicy: Never
      {{ if .Values.rbac.enabled }}
      serviceAccountName: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
      {{- end }}
      containers:
        - image: {{ .Values.prePuller.hook.image.name }}:{{ .Values.prePuller.hook.image.tag }}
          name: pre-puller
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DAEMONSET_SPEC
              {{ $daemonsetName := printf "pre-pull-%s-%d-%d" .Release.Name .Release.Revision .Release.Time.Seconds }}
              value: {{ toJson (fromYaml (include "jupyterhub.prePuller.daemonset" (dict "name" $daemonsetName "top" .))) | quote }}
            - name: IMAGE
              value: "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"
              {{ range $key, $value := .Values.prePuller.hook.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
              {{ end }}
{{ end }}
