{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "jupyterhub.ingress.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
  defaultBackend:
    service:
      name: proxy-public
      port:
        name: http
  {{- else }}
  backend:
    serviceName: {{ include "jupyterhub.proxy-public.fullname" . }}
    servicePort: 80
  {{- end }}
  {{- if .Values.ingress.hosts }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.hub.baseUrl }}{{ $.Values.ingress.pathSuffix }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ include "jupyterhub.proxy-public.fullname" $ }}
              servicePort: 80
            {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
