{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: 8000
      {{ if .Values.ingress.host -}}
      host: {{ .Values.ingress.host }}
      {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
