{{- if .Values.singleuser.image.pullSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: singleuser-image-credentials
  labels:
    {{- $_ := merge (dict "componentSuffix" "-image-credentials") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.singleuser.image.pullSecret.dockerConfigJson }}
{{- end }}
