# This secret is used for a pytest test of hub.existingSecret
kind: Secret
apiVersion: v1
metadata:
  name: test-hub-existing-secret
type: Opaque
stringData:
  JupyterHub.cookie_secret: fff999
  CryptKeeper.keys: fff999
  values.yaml: |
    singleuser:
      extraLabels:
        test-self-managed-secret: ok
