# Default values for jupyterhub.
# This is a YAML-formatted file.

# hub is the main JupyterHub server
hub:
  service:
    type: ClusterIP
  baseUrl: /
  cookieSecret:
  publicURL:
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  activeServerLimit:
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName:
    url:
  labels: {}
  extraConfig: ''
  extraConfigMap: {}
  extraEnv: {}
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  image:
    name: jupyterhub/k8s-hub
    tag: generated-by-chartpress
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  services: {}
  imagePullPolicy: IfNotPresent
  pdb:
    enabled: true

# rbac is role based access control.
# **caution** disabling rbac will give root access.
rbac:
  enabled: true

# proxy is a user-facing object for user access to JupyterHub 
proxy:
  secretToken: ''
  service:
    type: LoadBalancer
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 3.0.0
      pullPolicy: IfNotPresent
    cmd:
      - configurable-http-proxy
      - --ip=0.0.0.0
      - --port=8000
      - --api-ip=0.0.0.0
      - --api-port=8001
      - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
      - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)/hub/error
      - --log-level=debug
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.9.0
      pullPolicy: IfNotPresent
    proxyBodySize: 64m
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      # We need a couple of fixes related to ingress.provider that are in master
      # When 0.1.6 is released, switch to that!
      tag: master-2368
    resources: {}
  labels:
  nodeSelector: {}
  pdb:
    enabled: true
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    hosts: []


# auth is the authenticator used e.g. Google OAuth secrets
auth:
  # type is the specific authenticator used by the hub
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password:
  state:
    enabled: false
    cryptoKey:

# singleuser is the Jupyter singleuser notebook server
singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: generated-by-chartpress
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 1000
  serviceAccountName:
  schedulerStrategy:
  storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: generated-by-chartpress
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl:

# prePuller is used to pre-pull images to nodes and decrease user startup time
prePuller:
  hook:
    enabled: true
    extraEnv: {}
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: generated-by-chartpress
  continuous:
    enabled: false
  pause:
    image:
      name: gcr.io/google_containers/pause
      tag: '3.0'

# ingress is the object used to manage external access to the cluster
ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls:

# cull is the service used to remove inactive user notebook pods
cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
