# Default values for jupyterhub-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of this installation. Will be used to create namespace
# and storageclass. Must be a valid DNS label
# HACK: need to get rid of this, purely use --namespace only
name: null

# Deprecated, use proxy.secretToken instead
token:
  proxy: null

hub:
  service:
    type: CluseterIP
  baseUrl: "/"
  cookieSecret: null
  publicURL: null
  db:
    type: sqlite-pvc
    url: null
  labels: null
  extraConfig: null
  image:
    name: jupyterhub/k8s-hub
    tag: v0.3.1
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi

proxy:
  secretToken: 'generate with openssl rand -hex 64'
  service:
    type: LoadBalancer
  image:
    name: jupyterhub/configurable-http-proxy
    tag: 2.0.1
  cmd: 
    - configurable-http-proxy
    - --ip=0.0.0.0
    - --port=8000
    - --api-ip=0.0.0.0
    - --api-port=8001
    - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
    - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  labels: null

ingress:
  enabled: True


# Google OAuth secrets
auth:
  type: dummy
  dummy:
    password: null

singleuser:
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks: null
  storage:
    type: dynamic
    capacity: 10Gi
    homeMountPath: /home/jovyan
    # type: hostPath
    # homeHostPathTemplate: /data/project/paws/userhomes/{userid}
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.3.1
  cpu:
    limit: null
    guarantee: null
  memory:
    limit: null
    guarantee: 1G
  cmd: jupyterhub-singleuser

prePuller:
  enabled: true
  image:
    name: yuvipanda/image-allnodes-puller
    tag: v0.8

cull:
  enabled: true
  timeout: 3600
  every: 600

statsd:
  enabled: false
  port: 8125
  host: statsd
  prefix: jupyterhub

admin:
  access: true
  users: null
