---
name: Publish

on:
  push:

jobs:

  publish:
    if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # chartpress requires the full history
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies and run chartpress
        run: pip install --no-cache-dir -r dev-requirements.txt
      - name: Publish chart
        run: |
          . ./ci/common
          ./ci/publish
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
