# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test docker multiarch build

# Trigger the workflow's on all PRs and pushes so that other contributors can
# run tests in their own forks. Avoid triggering these tests on changes to
# documentation only changes.
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - "**/test-docs.yaml"
      - "**.md"
      - "**/schema.yaml"
  push:
    paths-ignore:
      - "doc/**"
      - "**/test-docs.yaml"
      - "**.md"
      - "**/schema.yaml"
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

jobs:
  # TODO: this is just a quick test to check the arm64 docker images
  # Based on
  # https://github.com/docker/build-push-action/blob/v2.3.0/docs/advanced/local-registry.md
  # https://github.com/docker/build-push-action/blob/v2.3.0/docs/advanced/multi-platform.md
  build_images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install chartpress
        run: pip install chartpress

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action/tree/v1.8.0#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to local registry
        run: >-
          chartpress --push --tag 0.0.1-dev
          --builder docker-buildx
          --platform linux/amd64 --platform linux/arm64
          --image-prefix ghcr.io/${{ github.repository_owner }}/z2jh-
