# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test docs

# Trigger the workflow's on all PRs and pushes so that other contributors can
# run tests in their own forks.
on:
  pull_request:
    paths:
      - "doc/**"
      - "**/test-docs.yaml"
  push:
    paths:
      - "doc/**"
      - "**/test-docs.yaml"
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  linkcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # chartpress is used by doc/conf.py, part of doc/doc-requirements.txt,
          # and requires information about the latest tagged commit, which
          # requires the git history.
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install deps
        run: pip install --no-cache-dir -r doc/doc-requirements.txt

      - name: Build and run linkcheck
        run: |
          cd doc
          echo ---
          echo Running: make html
          echo ---
          make html SPHINXOPTS='--color'
          echo ---
          echo Running: make linkcheck -W --keep-going
          echo ---
          make linkcheck SPHINXOPTS='--color -W --keep-going'
        # Make the job not fail if this step fail. The GitHub UI will due to
        # this signal the job to be green even though it has failures though, so
        # manual inspection is needed at the moment. A related ticket to improve
        # this is open.
        #
        # ref: https://github.com/actions/toolkit/issues/399
        continue-on-error: true
